function data()
return {
	en = {
		["mod_name"] = "DB Class 120",
		["mod_desc"] = "The 120 series is the first series-produced three-phase locomotive in the world and should replace all other series at the time. The locomotives were also able to run InterCity trains at a planned speed of 200 km/h. The series delivery of the machines began in 1984 and only differed in small parts from the pre-series locomotives. However, all series locomotives were designed for 200 km/h. After the rail reform, the locomotives came to the DB long-distance transport division, some locomotives were converted to the 120.2 series and received equipment for regional transport. The machines have been phased out and scrapped since 2016, but are still in use. The technology of the ICE power heads was developed from the technology of the BR 120, so that it can be regarded as a milestone in vehicle development.\nSince July 5, 2020 the Class 120 is retired from the active service at DB Fernverkehr.\n\nAvailability: from 1979 / from 1984\nMaximum speed: 160 km/h / 200 km/h\nPower: 5600 kw\nTraction: 340 kN",

        ["BR120_menu"] = "Class 120",
        ["BR120.0_name"] = "Class 120.0",
        ["BR120.1_name"] = "Class 120.1",
        ["BR120.2_name"] = "Class 120.2",
        ["BR120.5_name"] = "Class 120.5",
        ["BR120.0_005_name"] = "Class 120 005",
        ["BR752_name"] = "Class 752",
		["BR120.0_desc"] = "From 1979, the pre-series machines of the 120 series were delivered for testing. In addition to the 120 005, the machines were approved for only 160 km/h. The 120 002 set a world record in 1980 with a top speed of 231 km/h. It was not until 1987 that the first series locomotives were delivered.",
        ["BR120.0_ob_desc"] = "This paint job did not exist at the Deutsche Bundesbahn, it was only painted at a model train manufacturer.",
        ["BR120.0_abb_desc"] = "BR 120 004 with advertising for a test with disc brakes on the locomotive.",
        ["BR120.0_aeg_desc"] = "BR 120 002 in test operation by AEG.",
		["BR120.0_or_desc"] = "Pre-series locomotive in orient red paint. After delivery in red / ivory, the locomotives were also given the new look of the Deutsche Bundesbahn from 1986.",
        ["BR120.0_or_DBAG_desc"] = "Pre-series locomotive in orient red paint from DB AG. All pre-series locomotives were retired by the end of 2002 and no longer painted in traffic red.",
        ["BR752_vr_desc"] = "The 120 series was partially handed over to DB Systemtechnik to test new technologies. From there it was also used in regular service and was painted traffic red, but was classified as the 752 series.",
		["BR120.0_005_desc"] = "The engine 005 is a very special example among the prototypes. The locomotive was designed for a top speed of 200 km/h right from the start. In addition, the shape of the head was optimized by filling the roof, attaching aprons and lowering the kink. Until the delivery to the DB, all changes were reversed. The machine only kept the deep-drawn kink throughout its life and could be recognized from it. As a result, the red color separating edge sloped from the driver's door to the front.",
        ["BR120.0_005_or_desc"] = "Locomotive 120 005 in oriental red livery. Due to the single-color paintwork, the lower crease in the front was no longer immediately apparent.",
        ["BR120.0_005_or_DBAG_desc"] = "The 120 005 was rebuilt in 1992 to test new technologies and is now in the Weimar Railway Museum. All pre-series locomotives were retired by the end of 2002 and no longer painted in traffic red.",
        ["BR120.1_or_desc"] = "Series locomotives of the BR 120 were delivered from 1987. They differed little from the pre-series locomotives. All locomotives were delivered in the current color scheme orient red.",
        ["BR120.1_bw_desc"] = "An advertisement for the state of Baden-Württemberg with this slogan devised by the Scholz & Friends agency. In addition to the BR 120, the BR 101 was also partially wrapped with this advertisement.",
        ["BR120.1_or_DBAG_desc"] = "With the takeover by Deutsche Bahn AG in 1994, the still current orient red color scheme was given the new DB AG logo.",
        ["BR120.1_vr_desc"] = "From 1996, the traffic red color scheme was introduced and since the BR 120 was used in high-quality InterCity and passenger trains, this paint was quickly missed.",
        ["BR120.1_mmw_desc"] = "Advertising foil for Märklin model train company.",
        ["BR120.5_mess_desc"] = "From 2013, the locomotives of DB Systemtechnik were repainted in yellow and listed as series 120.5. The two locomotives were renumbered 120.1 back in 2016.",
        ["BR120.2_vr_desc"] = "For the traffic around Rostock, some locomotives were equipped with a local transport package, which among other things included a train destination indicator. These locomotives were listed as BR 120.2 and were used from Rostock and Aachen until 2018.",
		},
	de = {
		["mod_name"] = "DB BR 120",
		["mod_desc"] = "Die Baureihe 120 ist die erste in Serie gebaute Drehstrom-Lokomotive der Welt und sollte zu der Zeit alle anderen Baureihen ersetzen. Mit geplanten 200 km/h konnten die Loks auch InterCity-Züge bespannen. Ab 1984 begann die Serienlieferung der Maschinen, die sich nur in geringen Teilen von den Vorserienloks unterschied. Allerdings waren alle Serienloks für 200 km/h ausgelegt. Nach der Bahnreform kamen die Loks zum Bereich DB Fernverkehr, einige Loks wurden zur Baureihe 120.2 umgebaut und erhielten eine Ausrüstung für den Regionalverkehr. Seit 2016 werden die Maschinen nach und nach ausgemustert und verschrottet, sie sind allerdings immer noch im Einsatz. Die Technik der ICE-Triebköpfe wurde aus der Technik der BR 120 entwickelt, so dass sie als Meilenstein in der Fahrzeugentwicklung angesehen werden kann.\nSeit 5.Juli 2020 ist die BR 120 aus dem aktiven Dienst bei DB Fernverkehr ausgeschieden.\n\nVerfügbarkeit: ab 1979 / ab 1984\nHöchstgeschwindigkeit: 160 km/h / 200 km/h\nLeistung: 5600 kw\nAnfahrzugkraft: 340 kN",

        ["BR120_menu"] = "BR 120",
        ["BR120.0_name"] = "BR 120.0",
        ["BR120.1_name"] = "BR 120.1",
        ["BR120.2_name"] = "BR 120.2",
        ["BR120.5_name"] = "BR 120.5",
        ["BR120.0_005_name"] = "BR 120 005",
        ["BR752_name"] = "BR 752",
		["BR120.0_desc"] = "Ab dem Jahr 1979 wurden die Vorserien-Maschinen der Baureihe 120 zur Erprobung ausgeliefert. Außer der 120 005 waren die Maschinen für nur 160 km/h zugelassen. Die 120 002 stellte im Jahr 1980 einen Weltrekord auf mit 231 km/h Höchstgeschwindigkeit. Es dauerte bis 1987 bevor die erste Serienloks ausgeliefert wurden.",
		["BR120.0_or_desc"] = "Vorserienlok in orientroter Lackierung. Nach der Auslieferung in rot/elfenbein wurden die Loks ab 1986 auch in den neuen Look der Bundesbahn überführt.",
        ["BR120.0_or_DBAG_desc"] = "Vorserienlok in orientroter Lackierung der DB AG. Alle Vorserienloks wurden bis Ende 2002 ausgemustert und nicht mehr in verkehrsrot lackiert.",
        ["BR120.0_ob_desc"] = "Diese Lackierung existierte bei der Deutschen Bundesbahn nicht, sie war nur bei einem Modellbahnhersteller lackiert worden.",
        ["BR120.0_abb_desc"] = "BR 120 004 mit Werbung für einen Versuch mit Scheibenbremsen an der Lokomotive.",
        ["BR120.0_aeg_desc"] = "BR 120 002 im Erprobungseinsatz der Firma AEG.",
        ["BR752_vr_desc"] = "Die Baureihe 120 wurde teilweise an die DB Systemtechnik abgegeben um neue Technologien zu erproben. Sie wurde von dort aber auch im regulären Streckendienst eingesetzt und war verkehrsrot lackiert, allerdings als Baureihe 752 eingereiht.",
		["BR120.0_005_desc"] = "Bei der Lok 005 handelt es sich um ein ganz besonderes Exemplar unter den Prototypen. Die Lok war von Anfang an für eine Höchstgeschwindigkeit von 200 km/h ausgelegt. Außerdem wurde die Kopfform optimiert, indem man das Dach verspachtelte, Schürzen anbaute und den Knick tieferzog. Bis zur Ablieferung an die DB wurden alle Änderungen aber rückgängig gemacht. Nur den tiefergezogenen Knick behielt die Maschine zeitlebens und war  daran zu erkennen. Dadurch bedingt verlief die rote Farbtrennkannte ab der Fahrertür zur Front abfallend.",
        ["BR120.0_005_or_desc"] = "Lok 120 005 in orientroter Farbgebung. Durch die einfarbige Lackierung fiel der tiefere Knick in der Front nicht mehr gleich ins Auge.",
        ["BR120.0_005_or_DBAG_desc"] = "Die 120 005 wurde bereit 1992 umgebaut um neue Technologien zu erproben und steht heute im Eisenbahnmuseum Weimar. Alle Vorserienloks wurden bis Ende 2002 ausgemustert und nicht mehr in verkehrsrot lackiert.",
        ["BR120.1_or_desc"] = "Ab 1987 wurden die Serienloks der BR 120 ausgeliefert. Sie unterschieden sich nur wenig von den Vorserienloks. Alle Loks wurden im aktuellen Farbschema orientrot abgeliefert.",
        ["BR120.1_bw_desc"] = "Für das Land Baden-Württemberg werben sollten die mit dem von der Agentur Scholz&Friends erdachten Werbespruch. Neben der BR 120 wurde auch die BR 101 teilweise mit dieser Werbung foliert.",
        ["BR120.1_or_desc"] = "Ab 1987 wurden die Serienloks der BR 120 ausgeliefert. Sie unterschieden sich nur wenig von den Vorserienloks. Alle Loks wurden im aktuellen Farbschema orientrot abgeliefert.",
        ["BR120.1_or_DBAG_desc"] = "Mit Übernahme durch die Deutsche Bahn AG wurde 1994 das noch aktuelle Farbschema orientrot mit dem neuen Logo der DB AG versehen.",
        ["BR120.1_vr_desc"] = "Ab 1996 wurde das verkehrsrote Farbschema eingeführt und da die BR 120 im hochwertigen InterCity- und Reisezugverkehr einsetzt wurde, bekam sie diese Lackierung auch recht schnell verpaßt.",
        ["BR120.1_mmw_desc"] = "Werbelok der Firma Märklin.",
        ["BR120.5_mess_desc"] = "Die Loks der DB Systemtechnik wurden ab 2013 in gelb umlackiert und als Baureihe 120.5 geführt. Schon 2016 wurden die beiden Loks wieder in 120.1 umgenummert.",
        ["BR120.2_vr_desc"] = "Für den Verkehr rund um Rostock wurden einige Loks mit einem Nahverkehrspaket ausgerüstet, was u.a. einen Zugzielanzeiger beinhaltete. Diese Loks wurden als BR 120.2 geführt, wurden von Rostock und Aachen aus bis 2018 eingesetzt.",
        ["BR120.5_bt_desc"] = "Die Lok 120 153 wurde 2005 an die DB Systemtechnik zu Meßfahrten übergeben und dort als 120 501 bezeichnet. Seit 2018 ist sie wieder als 120 153 unterwegs.",
        ["BR120.5_zdf_desc"] = "Die Lok 120 151 war zwischen 1997 und 2010 mit einer Beklebung für das ZDF unterwegs.",
        ["BR120.1_sandwich1_name"] = "BR 120.1 - Sandwich vorne",
        ["BR120.1_sandwich1_desc"] = "Entweder um ohne Steuerwagen zu fahren oder um die Traktionsleistung zu erhöhen, fahren einige Züge im Sandwichbetrieb, in der Schweiz als Doppelpendelzug bezeichnet. Dadurch hängt jeweils am Anfang und Ende des Zuges eine Lok mit dem jeweils äußeren gehobenen Stromabnehmer. Lok für den Sandwich-Betrieb vorne.",
        ["BR120.1_sandwich2_name"] = "BR 120.1 - Sandwich hinten",
        ["BR120.1_sandwich2_desc"] = "Entweder um ohne Steuerwagen zu fahren oder um die Traktionsleistung zu erhöhen, fahren einige Züge im Sandwichbetrieb, in der Schweiz als Doppelpendelzug bezeichnet. Dadurch hängt jeweils am Anfang und Ende des Zuges eine Lok mit dem jeweils äußeren gehobenen Stromabnehmer. Lok für den Sandwich-Betrieb hinten.",
        ["BR120.1_abschied1_name"] = "BR 120.1 Abschiedsfahrt (Sandwich vorne)",
        ["BR120.1_abschied1_desc"] = "Die Deutsche Bahn hat am 5. Juli 2020 die Baureihe 120 aus dem aktiven Dienst im Fernverkehr entlassen. Der letzte Zug war mit zwei Loks mit besonderen Folierungen versehen. Lok für den Sandwich-Betrieb vorne.",
        ["BR120.1_abschied2_name"] = "BR 120.1 Abschiedsfahrt (Sandwich hinten)",
        ["BR120.1_abschied2_desc"] = "Die Deutsche Bahn hat am 5. Juli 2020 die Baureihe 120 aus dem aktiven Dienst im Fernverkehr entlassen. Der letzte Zug war mit zwei Loks mit besonderen Folierungen versehen. Lok für den Sandwich-Betrieb hinten.",
		},
}
end
